### ISSUE TITLE
[Bug] Missing save and setting icons in KDE menu

### ISSUE THREAD

**Issue by lucazade** [keeferrourke/la-capitaine-icon-theme#105]
There are no more save, save as and settings icons in menus.
Attached Kate screenshot with missing icons in red circles!
![screenshot_20170211_100613](https://cloud.githubusercontent.com/assets/1557010/22852697/47ba47aa-f042-11e6-87cb-4bc1f5b45e02.png)

**Comment by keeferrourke** [comment]
Yikes! Do you know have any idea which commit broke them? What the file names should be?

**Comment by lucazade** [comment]
No idea about filenames and which commit broke them. If you need I can try some old release.

**Comment by keeferrourke** [comment]
@lucazade was it a recent pull? I honestly don't have time to tackle this issue right away; it might be a few weeks before I can take a proper look.

**Comment by demoy** [comment]
I went through the stable releases,  _la-capitaine-icon-theme-0.3.2_ is the last version with functioning save/save-as icons. Strictly speaking icons are not missing, example _document-save_ is in the same place in version 0.3.2 and lastest commit [and that is _actions\22x22_ folder]. 

I replace the document-save icon with the _document-save-symbolic_  [both from latest commit, see below] and the save icons show up
![screenshot_20170213_140551](https://cloud.githubusercontent.com/assets/2396524/22898627/f5660d80-f1f5-11e6-8eb4-3f04daeb6f66.png)

Permissions are fine, so my conclusion is something is off in the files themselves. Heres what firefox output: 
![screenshot_20170213_141711](https://cloud.githubusercontent.com/assets/2396524/22898948/2645c9da-f1f7-11e6-81c8-cb5785bf9f7c.png)

Remove the _needs clarification_  label if this is satisfactory.

Here [Below] for completeness sake here is _la-capitaine-icon-theme/actions/22x22-light/document-revert.svg_ below working in firefox as the control case to _document save_.
![screenshot_20170213_141929](https://cloud.githubusercontent.com/assets/2396524/22899051/75e764bc-f1f7-11e6-95d5-ea756b02a043.png)

**Comment by keeferrourke** [comment]
Should be fixed now!

**Comment by demoy** [comment]
Fixed seen working below in Kate [application used by the riginal poster]
![screenshot_20170213_153631](https://cloud.githubusercontent.com/assets/2396524/22902198/4077bf06-f202-11e6-8dff-8fe90fecf364.png)

Now to uninstall Kate, ◔ᴗ◔.

**Comment by lucazade** [comment]
thanks for the works guys!
save icons now are ok.. settings icon instead is still missing here :(

**Comment by demoy** [comment]
Sorry About that I will run through to find it.

**Comment by keeferrourke** [comment]
The settings icons are likely likely to `22x22-*/document-properties.svg`; an icon that is broken as stated in #106. Will close this issue again when I fix it :)

**Comment by keeferrourke** [comment]
@lucazade pull the latest commits and let me know if the settings icon has been fixed :)

**Comment by lucazade** [comment]
@keeferrourke fixed now! thanks a lot :)
