### ISSUE TITLE
[Bug] List of broken icons

### ISSUE THREAD

**Issue by demoy** [keeferrourke/la-capitaine-icon-theme#106]
Related to [Missing save and setting icons in KDE menu](https://github.com/keeferrourke/la-capitaine-icon-theme/issues/105) [Edit: this is my karma for getting it close] here is a list of  icons with faulty xml I found using firefox. I will organize these icons base on directory, atmost 1 directory per post.

[included are screenshots for each item because I am assuming the column & line numbers will be useful, if not tell me and i'll stop]

broken in _action/22x22-light/_

- [x] document-properties.svg

![screenshot_20170213_171220](https://cloud.githubusercontent.com/assets/2396524/22905843/e2ad8a64-f20f-11e6-83ef-3ac0507c317e.png)

- [x] adjustrgb.svg

![screenshot_20170213_171531](https://cloud.githubusercontent.com/assets/2396524/22905899/12b95422-f210-11e6-9b0f-73416bfb1f92.png)

- [x] align-horizontal-right-out.svg

![screenshot_20170213_171716](https://cloud.githubusercontent.com/assets/2396524/22905955/50643a6c-f210-11e6-8b42-d9b0c5a9bf9a.png)

- [x] align-horizontal-right-to-anchor.svg

![screenshot_20170213_171905](https://cloud.githubusercontent.com/assets/2396524/22906010/9e4cbcea-f210-11e6-91c2-210e67247721.png)

- [x] align-horizontal-top-out.svg

![screenshot_20170213_172109](https://cloud.githubusercontent.com/assets/2396524/22906065/dfb52d0c-f210-11e6-936d-9b90a881b3ea.png)

- [x] align-vertical-bottom-out.svg

![screenshot_20170213_172357](https://cloud.githubusercontent.com/assets/2396524/22906140/3975bfc8-f211-11e6-97d7-cccae9d21979.png)

- [x] align-vertical-bottom.svg

![screenshot_20170213_172526](https://cloud.githubusercontent.com/assets/2396524/22906185/6f5f6544-f211-11e6-991a-e3af3d6fe9ed.png)

- [x] align-vertical-top-to-anchor.svg

![screenshot_20170213_172912](https://cloud.githubusercontent.com/assets/2396524/22906321/f6235806-f211-11e6-9dd4-5cb7befaf0b5.png)

- [x] color-gradient.svg

![screenshot_20170213_173003](https://cloud.githubusercontent.com/assets/2396524/22906349/143a39fe-f212-11e6-879e-59a6e831e77b.png)

- [x] depth16to8.svg

![screenshot_20170213_173103](https://cloud.githubusercontent.com/assets/2396524/22906381/3e19701e-f212-11e6-8439-37be7065c87f.png)

- [x] depth8to16.svg

![screenshot_20170213_173213](https://cloud.githubusercontent.com/assets/2396524/22906425/635411a4-f212-11e6-9631-3b21d054114e.png)

- [x] rating.svg

![screenshot_20170213_173401](https://cloud.githubusercontent.com/assets/2396524/22906483/a37f1bf2-f212-11e6-8e2d-dd994a09f981.png)

- [x] utilities.svg

![screenshot_20170213_173519](https://cloud.githubusercontent.com/assets/2396524/22906515/d25822ca-f212-11e6-9db9-b25cd0f9d4ee.png)

Also in 22x22, _mail-read.svg_ is symbolic link to _mail.svg_; which does not exist.

**Comment by demoy** [comment]
broken in _actions/symbolic/_

media-playlist-consecutive-rtl-symbolic.svg

![screenshot_20170213_175059](https://cloud.githubusercontent.com/assets/2396524/22906981/007732e8-f215-11e6-8792-77c69c5d13ef.png)

media-playlist-consecutive-symbolic.svg

![screenshot_20170213_175327](https://cloud.githubusercontent.com/assets/2396524/22907077/5e9ac934-f215-11e6-9a55-eaba8f760355.png)

I wont do _22x22-dark_, since I assume its auto generated from 22x22-light correct me if i'm wrong.

**Comment by demoy** [comment]
broken in status/symbolic/

media-playlist-consecutive-symbolic.svg

**Comment by keeferrourke** [comment]
@demoy I've updated your comments with checkboxes so I can track my progress as I fix these issues.

> I wont do 22x22-dark, since I assume its auto generated from 22x22-light correct me if i'm wrong.

You're correct, `22x22-dark` was generated from `22x22-light`; each `*-dark` directory was created as a copy of the light icons, and then a simple regex replace was run over every file. Any light icon's dark counterpart is very likely to be broken as well.

... It was probably this replacement that broke these files. Ironically, they all display correctly under GNOME (I guess the svg rasterizer allows for errors and isn't strict) &mdash; which is why I didn't notice the broken files. Working on a fix now.

**Comment by keeferrourke** [comment]
> broken in status/symbolic/
> - media-playlist-consecutive-symbolic.svg

This icon shouldn't even exist :^)

**Comment by keeferrourke** [comment]
Everything on this issue should now be fixed :)

**Comment by demoy** [comment]
15 of 16 done,  _adjustrgb.svg_ still wonky -
![screenshot_20170214_125302](https://cloud.githubusercontent.com/assets/2396524/22941875/35ab7618-f2b5-11e6-819d-cc338779d66e.png)

**Comment by kun-zhou** [comment]
![screenshot_20170214_140546](https://cloud.githubusercontent.com/assets/19158151/22944578/2150d578-f2bf-11e6-9a9c-382719cea084.png)
Here, it seems like three icons in KWrite is still missing. Save, Save as, and find&Replace icons. I am running the latest icon pack from git as of this morning.

**Comment by keeferrourke** [comment]
> 12 of 13 done, adjustrgb.svg still wonky -

Huh. Will take another look.

**Comment by keeferrourke** [comment]
> Here, it seems like three icons in KWrite is still missing. Save, Save as, and find&Replace icons. I am running the latest icon pack from git as of this morning.

Aghhhhh I'll go through the relevant icons and try to get them fixed ASAP. They should all be under `actions/`. If @demoy can help locate the broken icons as before, it would be super appreciated ^_^

**Comment by keeferrourke** [comment]
Definitely fixed the `adjustrgb` icons this time.

**Comment by demoy** [comment]
@kun-zhou the icon cache might be outdated, do any of the following:
A. select the icon theme again in system setting and apply.
B. log-out, then log-in.

If you do option A remember to restart any instances of kwrite you have open.
![screenshot_20170214_170724](https://cloud.githubusercontent.com/assets/2396524/22951684/14edd70e-f2d8-11e6-8123-8e57f8a03c66.png)

**Comment by demoy** [comment]
I maybe kontes_close.svg [A symbolic link] in action/22x22 was intended to be knotes_close.svg

**Comment by kun-zhou** [comment]
@demoy Okay, I rebooted and it the icons are updated. Thanks!

**Comment by keeferrourke** [comment]
@demoy yup, fixed.
