### ISSUE TITLE
Some KDE dark icon not visible

### ISSUE THREAD

**Issue by now-im** [keeferrourke/la-capitaine-icon-theme#338]
![35767117-0675b030-0910-11e8-9de3-5a3511bc5872](https://user-images.githubusercontent.com/22009014/35769171-13db7770-0931-11e8-9462-33723be67509.jpeg)
![35767118-06b6c19c-0910-11e8-9868-7e5ee0a2037e](https://user-images.githubusercontent.com/22009014/35769172-14206c54-0931-11e8-813a-55b3e15ae9d9.jpeg)

**Comment by keeferrourke** [comment]
Always fighting with KDE... rip. Was this working before? Do you know what commit broke the icons?

**Comment by now-im** [comment]
No idea. For sometime  I was using white theme. So after shiftinh to thedark. I see the problem

**Comment by Riotism** [comment]
I pushed some commits that implement KDE's color scheme to the picture folder icon. Please test if it's working.

**Comment by now-im** [comment]
not fixed. @DarkknightAK provided a demo previously that shows the standard method.
#238

**Comment by Riotism** [comment]
Pushed more commits. Please test again.

**Comment by now-im** [comment]
No, As far as I know this should not look like this:

```
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="16" height="16">
	<defs>
		<style type="text/css" id="current-color-scheme">
			.ColorScheme-Text {color:#f2f2f2;}
		</style>
	</defs>
	<path class="ColorScheme-Text" d="m 1.201457,0.39249965 c -0.447871,0 -0.808957,0.392639 -0.808957,0.88159835 v 13.450153 c 0,0.488959 0.361086,0.883249 0.808957,0.883249 h 13.597086 c 0.44787,0 0.808957,-0.39429 0.808957,-0.883249 V 1.2740981 c 0,-0.48895945 -0.361087,-0.88159845 -0.808957,-0.88159845 z M 9.8077717,5.8290223 13.071667,10.170977 H 2.928333 l 2.535834,-3.2539897 1.807772,2.175931 z" fill="currentColor" />
</svg>
```

Rather:

```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16">
  <defs id="defs3051">
    <style type="text/css" id="current-color-scheme">
      .ColorScheme-Text {
        color:#f2f2f2;
      }
      </style>
  </defs>
 <path 
           style="fill:currentColor;fill-opacity:1;stroke:none" 
           class="ColorScheme-Text"
        d="m 1.201457,0.39249965 c -0.447871,0 -0.808957,0.392639 -0.808957,0.88159835 v 13.450153 c 0,0.488959 0.361086,0.883249 0.808957,0.883249 h 13.597086 c 0.44787,0 0.808957,-0.39429 0.808957,-0.883249 V 1.2740981 c 0,-0.48895945 -0.361087,-0.88159845 -0.808957,-0.88159845 z M 9.8077717,5.8290223 13.071667,10.170977 H 2.928333 l 2.535834,-3.2539897 1.807772,2.175931 z"
     />
</svg>
```

**Comment by Riotism** [comment]
You are not using the latest commit. The last commit (bbdd810) uses CSS fill not the XML fill.

**Comment by now-im** [comment]
Using the latest commit. Problem not fixed.
![screenshot_20180206_211123](https://user-images.githubusercontent.com/22009014/35866909-974aef16-0b82-11e8-8511-987bd6134255.png)

**Comment by Riotism** [comment]
It works on my machine. Your screenshot also shows problem with the audio folder icon, which was a fixed bug. Have you refreshed your icon cache?

![screenshot_20180207_103458](https://user-images.githubusercontent.com/7264350/35895491-a60971ec-0bf2-11e8-9f38-6fde26b2aa13.png)

**Comment by now-im** [comment]
Yes, problem fixed. Generally rebooting the system solves this problem. After deleting the `cache` it works now.
